# Generated by Django 5.1.3 on 2024-12-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20230509_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the discussion', max_length=200)),
                ('date', models.DateField(help_text='Enter the date of the discussion')),
                ('time', models.TimeField(help_text='Enter the time of the discussion')),
                ('link', models.URLField(help_text='Enter the Google Meet link', max_length=500)),
            ],
        ),
    ]
