# Generated by Django 5.1.3 on 2025-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('courses_provided', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='institution_images/')),
            ],
        ),
    ]
