# Generated by Django 5.1.4 on 2025-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_course_id_alter_customer_id_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
