# Generated by Django 5.1.3 on 2025-01-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_course_id_alter_customer_id_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='steps',
            field=models.CharField(default='steps', max_length=200),
        ),
    ]
