# Generated by Django 5.1.3 on 2025-01-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_question_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='steps',
        ),
    ]
